/*
// Get all suppliers
export const ALL_SUPPLIER_REQUEST = "ALL_SUPPLIER_REQUEST";
export const ALL_SUPPLIER_SUCCESS = "ALL_SUPPLIER_SUCCESS";
export const ALL_SUPPLIER_FAIL = "ALL_SUPPLIER_FAIL";

// Supplier details
export const SUPPLIER_DETAILS_REQUEST = "SUPPLIER_DETAILS_REQUEST";
export const SUPPLIER_DETAILS_SUCCESS = "SUPPLIER_DETAILS_SUCCESS";
export const SUPPLIER_DETAILS_FAIL = "SUPPLIER_DETAILS_FAIL";

// Create new supplier
export const SUPPLIER_CREATE_REQUEST = 'SUPPLIER_CREATE_REQUEST';
export const SUPPLIER_CREATE_SUCCESS = 'SUPPLIER_CREATE_SUCCESS';
export const SUPPLIER_CREATE_FAIL = 'SUPPLIER_CREATE_FAIL';
export const SUPPLIER_CREATE_RESET = 'SUPPLIER_CREATE_RESET';


// Update supplier
export const SUPPLIER_UPDATE_REQUEST = "SUPPLIER_UPDATE_REQUEST";
export const SUPPLIER_UPDATE_SUCCESS = "SUPPLIER_UPDATE_SUCCESS";
export const SUPPLIER_UPDATE_RESET = "SUPPLIER_UPDATE_RESET";
export const SUPPLIER_UPDATE_FAIL = "SUPPLIER_UPDATE_FAIL";

// Delete supplier
export const SUPPLIER_DELETE_REQUEST = "SUPPLIER_DELETE_REQUEST";
export const SUPPLIER_DELETE_SUCCESS = "SUPPLIER_DELETE_SUCCESS";
export const SUPPLIER_DELETE_RESET = "SUPPLIER_DELETE_RESET";
export const SUPPLIER_DELETE_FAIL = "SUPPLIER_DELETE_FAIL";

// Clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";
*/